### ISSUE TITLE
Cypress screenshots with capture: fullPage isn't functional with cypress 13

### ISSUE THREAD

**Issue by justineschott** [argos-ci/argos#1143]
As a user, I want to screenshot and compare a `fullPage` of my webapp using argos and cypress 13.

### Motivation
There appears to be a change in functionality when moving from cypress 12 to 13. Previously, both the default `capture` option as well as setting a `capture` option of `fullPage` results in a full page being screenshot. Upon moving to cypress 13, the screenshot gets cut off.

### Detail
```
import '@argos-ci/cypress/support'

Cypress.Commands.add('argosChecks', (pageName) => {
	// give the page time to fully load/for elements to stop resizing and moving
	cy.wait(200)
	// take a screenshot of the page for argos visual testing
	cy.argosScreenshot(pageName)
})

it('should render welcome page', () => {
	cy.argosChecks('welcome-page')
})
```

**Comment by gregberge** [comment]
Hello @justineschott, I should be a Cypress issue but I heard some regression on Playwright at the same time, maybe a change into Chrome that could impact both libraries. Could you provide an example of a cut off screenshot? Does it have the good height with black or is it cropped like if `capture: "fullPage"` was completely ignored?

**Comment by gregberge** [comment]
@justineschott the screenshot could be cut in Cypress if you navigate to another page during the screenshot phase.
