### ISSUE TITLE
Select reference build manually and don't rely on Git anymore

### ISSUE THREAD

**Issue by gregberge** [argos-ci/argos#1151]
The idea is to be able to select the reference build manually (by accepting it) and to disconnect from Git completely. It was asked by a client. 

https://mail.google.com/mail/u/0/#search/k/KtbxLxglpmsCXHvHLVXnmDhhwwprlnHhnq

We need to document it.

**Comment by shipplix** [comment]
Hi @gregberge, any update on the progress of this issue or when it will be available in the pro plan?

**Comment by michalvenosrouvy** [comment]
Hi, what is the estimate time of this update? 
Without it argos is quite useless for us.

**Comment by gregberge** [comment]
It's actually released as https://argos-ci.com/changelog/2024-05-28-monitoring-mode
