### ISSUE TITLE
Partial screenshot upload 

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#1189]
As a user, I would like to be able to only upload a sub-set of my screenshots, based on the files that I know changed relative to the baseline.

### Motivation

At MUI, we take screenshots of React components. We should be able to create a webpack plugin that skip the emission of all the modules that didn't change in the git diff and that have not parent dependency. This would allow us to take/diff 10 screenshots per build rather than 1,000. So a gain of two orders of magnitude.

### Benchmarks

- https://www.chromatic.com/docs/turbosnap/
- This is the strategy used by Reframe, e.g. https://github.com/lewisl9029/radix-ui-primitives/pull/3 to significantly speed up the visual regression diffs.

**Comment by gregberge** [comment]
Hello @oliviertassinari, it's very interesting. It could dramatically speed up the build time for you! I will think about it and I keep you up to date.

**Comment by oliviertassinari** [comment]
To be fair, we don't have the bandwidth to update our screenshot generator to support this. However, I know Argos has one for different tools so I thought that I would open an issue. It could be a way for Argos to differentiate, I don't know if Chromatic does this for instance.

**Comment by gregberge** [comment]
Chromatic does it yes but they have the control over Storybook so it's integrated. https://www.chromatic.com/docs/turbosnap/

For Argos we can't make it automatic that's why it's not a urgent issue. For enterprise projects with lot of screenshots I think it's interesting.

**Comment by gregberge** [comment]
Not enough interest in this, closing it.
