### ISSUE TITLE
Playwright -- Error: Request body validation failed: data/screenshots/0/metadata must NOT have additional properties

### ISSUE THREAD

**Issue by videate-josh** [argos-ci/argos#1345]
As a user,

When I take a screenshot via Playwright and CI, I'm not expecting the following 

`Error: Request body validation failed: data/screenshots/0/metadata must NOT have additional properties`

### Motivation

Ever since we upgraded to the latest argos: `"@argos-ci/playwright": "^3.4.0",` we've seen occasional failures in CI

### Detail

We are using a shared method to take screenshots like this:
```typescript
(in the playwright test)
     await VideateEnv.screenshot(page, 'Snapshot All Personas');

(in the shared lib)
static async screenshot(page: Page, screenshotName: string) {
       ....
      await argosScreenshot(page, screenshotName, {
        argosCSS: `iframe#launcher { display: none; }`,
      });
}    
```

**Comment by gregberge** [comment]
@videate-josh I made a temporary fix to unblock you. I will investigate in detail what is the root cause of this. In the meantime it should not happen anymore.

**Comment by videate-josh** [comment]
Awesome - thank you @gregberge I appreciate the rapid response and turnaround.

**Comment by videate-josh** [comment]
@gregberge has this been released? I never saw a package update.

**Comment by gregberge** [comment]
I fixed it server side. So no need to update anything on your side.
