### ISSUE TITLE
HTTP 413 error when uploading artifacts

### ISSUE THREAD

**Issue by sidharthv96** [argos-ci/argos#1379]
As a user, I'm getting 413 error when running a large test suite. 

Is argos uploading all the screenshots at the `after:run` event? 

![image](https://github.com/user-attachments/assets/86ed037c-2c4c-45c3-9df7-163f97a86c48)

### Detail

Logs: https://github.com/mermaid-js/mermaid/actions/runs/10923451948/job/30321479565?pr=5825
PR: https://github.com/mermaid-js/mermaid/pull/5825

**Comment by gregberge** [comment]
It seems coming from Applitools isn't it?

**Comment by gregberge** [comment]
OK I see, you must have lot of screenshots to trigger an error like that. We only send screenshot names to the API and our limit is 10mo!

**Comment by sidharthv96** [comment]
That was fast 🤯 🫶
