### ISSUE TITLE
Dynamic reference branch

### ISSUE THREAD

**Issue by sidharthv96** [argos-ci/argos#1381]
As a user, I want my CI to select which branch to use as reference to my current build.

### Motivation

We have set `develop` as the default branch in mermaid. This works great with PRs, as everything is compared to develop. 
When doing releases, we need to test the screenshots with the current `master`, as a final sanity check.
This is currently done manually using Applitools. If we could specify which branch to use as reference from the CI, then we could use the target branch of every PR by default. So PRs to master would compare with master, PRs to develop would compare with develop. 

This would also allow us to do stacked PRs, where we have changes in PR X to develop, and we need to make a new PR Y to X, and see just those changes. 

### Detail

Might be related to https://github.com/argos-ci/argos/issues/1151
I saw a [CLI option in docs](https://argos-ci.com/docs/reference-build#select-a-custom-reference-using-cli), but we need a CI option.

**Comment by gregberge** [comment]
There is no issue about that, but I plan to do it very soon. The target branch of a PR will be used reference branch automatically.

**Comment by gregberge** [comment]
It's done: https://argos-ci.com/changelog/2024-10-08-multi-branches
