### ISSUE TITLE
Generate / view token

### ISSUE THREAD

**Issue by neoziro** [argos-ci/argos#165]
As a user, I can generate and view a token for my repositories.

**Comment by oliviertassinari** [comment]
Use the following as inspiration
- Builds
  https://sentry.io/argos/test/

- Build sample
  https://sentry.io/argos/test/issues/254508284/?sample

- Getting-started
  - https://sentry.io/argos/test/getting-started/javascript/
  - https://percy.io/Olivier/tutu

- Settings
  - Environment Variables
    - https://percy.io/Olivier/tutu/settings
    - https://sentry.io/argos/test/settings/keys/
