### ISSUE TITLE
Move JS client in another repository

### ISSUE THREAD

**Issue by neoziro** [argos-ci/argos#195]
As a developer I can commit on the client in a separated repository.

### Motivation

- Isolate dependencies
- Isolate tests
- Create specific issues
- Manage releases with GitHub

**Comment by oliviertassinari** [comment]
I would avoid following that path. I would rather filter part of the tests suite, release depending on the part of the code that changed.

**Comment by neoziro** [comment]
@oliviertassinari not possible on Heroku, not possible to view release in GitHub clearly, tools are not ready to do that. The cycle of the two products are completely different so it makes sense and it simpler for us.

**Comment by neoziro** [comment]
@oliviertassinari triggering a release on heroku for a change in the CLI is not good. Also waiting for all tests to pass for a change in the CLI is a waste of time and resources 🐻.

**Comment by oliviertassinari** [comment]
@neoziro Can't we aboard a release if don't find any relevant file changes? Can't we skip the tests? 💯  for the simplest solution. I'm not sure where it's. Code sharing is going to be an issue.

**Comment by neoziro** [comment]
Done in #213
