### ISSUE TITLE
Improve diff

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#198]
Builds with issues:
- `alpha background`✈️:
  - https://www.argos-ci.com/doctolib/doctolib/builds/1288
- `box-shadow`:
  - https://www.argos-ci.com/doctolib/doctolib/builds/1532
- `nochange?`:
  - https://www.argos-ci.com/doctolib/doctolib/builds/2231
  - https://www.argos-ci.com/doctolib/doctolib/builds/2950
- wft
  - https://www.argos-ci.com/callemall/material-ui/builds/4179
- `small image changes after compression`
  - https://www.argos-ci.com/algolia/instantsearch.js/builds/4431
  - https://www.argos-ci.com/algolia/react-instantsearch/builds/4735

**Comment by neoziro** [comment]
@oliviertassinari is it really solved?

**Comment by oliviertassinari** [comment]
I have found this one #333
