### ISSUE TITLE
Upgrade react-router to v4

### ISSUE THREAD

**Issue by neoziro** [argos-ci/argos#225]
### Motivation

Do not be blocked.

**Comment by oliviertassinari** [comment]
I would rather use next.js for the DX & UX.

**Comment by neoziro** [comment]
@oliviertassinari why not, Apollo + Next seems a good choice

**Comment by oliviertassinari** [comment]
Yeah, perfect for seed of iteration as a dev, performance as a user and SEO for the upcoming documentation.
