### ISSUE TITLE
Dogfooding

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#234]
As a user, I'm using a product used internally by their creators.

### Motivation

We are sending a simple and static image to Argos. It would be much better to start capturing screenshots of the actual product.

### Detail

I don't think that we need browserstack. A docker should be enough. Then we can use `selenium-webdriver` or a more abstracted solution like webdriverio or nightwatch.

**Comment by neoziro** [comment]
https://travis-ci.org/argos-ci/argos it's actually totally broken.
