### ISSUE TITLE
Track the argos-cli version

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#235]
As a user, I'm warned when I'm using an out of date version of  the cli.

### Motivation

So we can ask them to upgrade in the interface

**Comment by neoziro** [comment]
@oliviertassinari I think update-notifier does the job

**Comment by neoziro** [comment]
@oliviertassinari I think the true issue is to track server-side the version of the CLI used to upload screenshots

**Comment by oliviertassinari** [comment]
Yes, you are correct.
