### ISSUE TITLE
Warn when using the argos-cli with no matching screenshot

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#236]
As a user, I'm aware if no screenshot is found by the cli. 

### Motivation

I have been trying to setup an `argos-bootstrap` project, that's the first mistake I did and had no error about it.

**Comment by neoziro** [comment]
Also warn if the directory doesn't exist.

**Comment by neoziro** [comment]
https://sentry.io/argos/argos-client/issues/242700147/
