### ISSUE TITLE
Adding a default value for createdAt and updatedAt in PostgreSQL

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#251]

**Comment by neoziro** [comment]
@oliviertassinari is it possible? You mean default value?

**Comment by oliviertassinari** [comment]
Yes default value, that was your idea originally :)

**Comment by neoziro** [comment]
Yes I thought it was adding some createdAt and updatedAt column automatically, updatedAt cannot be easy handled by Postgres. So it's just adding a default value for all updatedAt / createdAt.
