### ISSUE TITLE
Diff UI: screenshot diff

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#26]
As a user, I can compare two screenshots using one of the following methods.

### Motivation

Helps better catching regression.

### Detail

- [ ] superposition:
![capture d ecran 2017-01-03 a 23 29 49](https://cloud.githubusercontent.com/assets/3165635/21625565/89c605b6-d20c-11e6-886e-8239f563034e.png)
- [ ] onion skin:
![capture d ecran 2017-01-03 a 23 29 35](https://cloud.githubusercontent.com/assets/3165635/21625554/81207716-d20c-11e6-858e-4865d72c735f.png)
- [ ] swipe: 
![capture d ecran 2017-01-03 a 23 29 03](https://cloud.githubusercontent.com/assets/3165635/21625542/738a2872-d20c-11e6-826c-e2c8b04489e6.png)
- [ ] flicker: https://github.com/Galooshi/happo/issues/170#issue-196468932

**Comment by neoziro** [comment]
@oliviertassinari I think it's a feature, to start superposition is good.

**Comment by neoziro** [comment]
#359 will address that.
