### ISSUE TITLE
Add an option for accepting a score > 0 as non error

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#261]

**Comment by neoziro** [comment]
I don't think it's a good way, a minimal change can be a problem (border red instead of border grey).

**Comment by oliviertassinari** [comment]
I know, but some users might want to reduce the noise and only be notified for major changes.
I think that we can be smart about the threshold. red -> grey are far in the color spectrum.

**Comment by oliviertassinari** [comment]
Also, we need a way to tolerate the inconsistence of environment in browserstack.

**Comment by neoziro** [comment]
We already talk about it, we need to be tolerant on variation of color, not
on variation of pixel.

**Comment by oliviertassinari** [comment]
A variation of pixel is a variation of color. We could potentially have two thresholds. One at the diff time to answer the following question. Has something changed? And another one at the notification time to answer the following question. Is that change significant?

**Comment by oliviertassinari** [comment]
I would rather focus on the first threshold as I think bring the more value.

**Comment by neoziro** [comment]
I disagree because adding this feature could degrade our product. I prefer to find an other way and don't introduce it. It looks like a quick win but it is in fact a long lose.
