### ISSUE TITLE
Handle uploaded screenshots with the same name

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#268]
As a user, the parent folder name is taken into account when uploading a file

### Motivation

https://www.argos-ci.com/callemall/material-ui/builds/2580

**Comment by neoziro** [comment]
It's relative to uploading from the CLI either from the server. We should do it at the same time because doing it without #186 is very difficult...

**Comment by oliviertassinari** [comment]
I'm gonna update the CLI tool to take the parent folder name into account. For instance that could looks like this: `demo-avatar/Avatar.png`.
