### ISSUE TITLE
Display progression in the UI

### ISSUE THREAD

**Issue by oliviertassinari** [argos-ci/argos#282]
As a user, I can see the status of ongoing background jobs and have a UI up to date without having the refresh the page.

### Motivation

Provides a better UX

### Detail

Pain point raised by @julien-meichelbeck

**Comment by julien-meichelbeck** [comment]
Please

**Comment by neoziro** [comment]
@oliviertassinari or add enough workers to be instant like ahah

**Comment by neoziro** [comment]
Linked to #359
