### ISSUE TITLE
Navigate through screenshots with your arrowkeys

### ISSUE THREAD

**Issue by amazingfondu** [argos-ci/argos#305]
En tant qu'utilisateur,
Ce serait cool de pouvoir naviguer entre les 2 screenshot et le diff via les flèches du clavier.
C'est une tannée de devoir ouvrir les 3 screenshots dans des onglets puis de naviguer parmis eux. Aucun navigateur n'a été optimisé pour rendre la navigation entre onglet rapide.

Bisous.

**Comment by oliviertassinari** [comment]
Voilà une belle user story

**Comment by neoziro** [comment]
Will be addressed in #359
