### ISSUE TITLE
Website: avatar + username breaks layout

### ISSUE THREAD

**Issue by Haroenv** [argos-ci/argos#338]
current site | stupid 1px hack
---|---
<img width="872" alt="screen shot 2017-07-14 at 12 27 48" src="https://user-images.githubusercontent.com/6270048/28208847-0ed77b44-6890-11e7-9caa-4c86881efdaa.png">|<img width="887" alt="screen shot 2017-07-14 at 12 27 36" src="https://user-images.githubusercontent.com/6270048/28208848-0effe688-6890-11e7-8757-721da49f56f9.png">

**Comment by oliviertassinari** [comment]
Closes with bf9240b79647e4724367e1d992dfc20a497b3ce8, thanks for the feedback.
