### ISSUE TITLE
Diff ou pas diff

### ISSUE THREAD

**Issue by isc** [argos-ci/argos#344]
Salut Olivier,

J'espère que tout se passe bien de ton côté et que la vie est belle.
Il paraît que ton retour sur la flakiness Argos pour Doctolib est que c'est Doctolib-side.
J'ai l'impression que je constate le contraire.
Prenons ce build https://www.argos-ci.com/doctolib/doctolib/builds/12257
Prenons les images https://s3.amazonaws.com/argos-screenshots-us/d5f6b4c35b33e9f89eacdf62d56d821b et https://s3.amazonaws.com/argos-screenshots-us/c07138273d05490bba06180430aef5f5 pour lesquelles la UI d'Argos me présente ce diff https://s3.amazonaws.com/argos-screenshots-us/dcd2a9de-34b5-4d07-846c-4bdc6ba61d0b.
Lorsque je lance `image-difference` en local, j'ai le résultat suivant :
```
✔ ~/Code/argos [master|…1] 
11:29 $ image-difference ~/Downloads/c07138273d05490bba06180430aef5f5.png ~/Downloads/d5f6b4c35b33e9f89eacdf62d56d821b.png diff.png

✔  No difference
```
Comment expliquer le diff présenté par Argos ? Aurais-tu une piste que je pourrais creuser dans la codebase d'Argos pour débugger ?

Merci d'avance pour ton retour

**Comment by oliviertassinari** [comment]
@isc Merci pour l'issue.

J'ai pris le point en bas à droite du fond bleu. On a les couleurs suivantes:
- 1ère image : `#0b94dc`
- 2ème image : `#1694de`

L'output de [image-difference](https://github.com/argos-ci/image-difference) va dépendre de la version de imagemagic installé. De ce que je me rappelle, Heroku a une version d'imagemagic installé par default, une version assez ancienne. Il faudrait que je regarde.
- En local j'ai `convert --version`:
> Version: ImageMagick 6.9.8-10 Q16 x86_64 2017-06-12 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
- Sur la CI on a `convert --version`:
> Version: ImageMagick 6.6.9-7 2017-03-14 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP

**Comment by isc** [comment]
Merci pour ton prompt retour Olivier.
On creuse côté screenshot en sortie de Browserstack.

**Comment by neoziro** [comment]
@isc Merci pour ton issue. Pour le moment on n'est plus trop actif sur le projet, on va voir ce qu'on en fait d'ici Janvier.

**Comment by matthieuprat** [comment]
Vous seriez OK pour utiliser un build-pack avec une version plus récente ?

```bash
heroku config:add IMAGE_MAGICK_VERSION="6.9.9-20"
heroku buildpacks:add --index 1 https://github.com/matthieuprat/heroku-buildpack-imagemagick
```

Je viens de tester le build pack une stack cedar-14, l'installation s'est bien passée.

**Comment by matthieuprat** [comment]
J'ai aussi fait le test sur Heroku-16 : 👌

**Comment by matthieuprat** [comment]
Excellente nouvelle ! Merci !
