### ISSUE TITLE
CI job is successful, when screenshots have the changes

### ISSUE THREAD

**Issue by alexeybondarenko** [argos-ci/argos#345]
Hi.
Thank you for the creation of Argos CI! 

I’ve been trying to use Argos CI for the project. I've used it to add the visual regression testing on storybook of the react application. 

The screenshots have been uploaded for the base branch (`develop`) and for the PR branch. In PR branch, I've modified the UI to have the changes in the screenshots and they exist. I've been expecting what the Argos CI process will be failed, but it's succeeded.

Could you help me? Maybe I'm doing something wrong or have the misunderstanding of some concepts of Argos CI

**Comment by oliviertassinari** [comment]
@alexeybondarenko Thanks for trying out our service! We assume that the default branch is `master`. Let me change it to `develop`. We miss the option to change such value in the UI.

**Comment by alexeybondarenko** [comment]
@oliviertassinari I would be appreciate to you. The build https://www.argos-ci.com/Syft-Application/syft2webclient/builds/12781

**Comment by oliviertassinari** [comment]
The build you linked was created on 2017-11-01 16:54:42.993+00 UTC, 30+ minutes ago.

**Comment by alexeybondarenko** [comment]
Sorry. I didn't see that you've updated the comment. I will re-run the CI and message you. Thanks.

**Comment by alexeybondarenko** [comment]
@oliviertassinari Thanks it works now! See you all

**Comment by oliviertassinari** [comment]
@alexeybondarenko You have some flakiness. You are not done yet 😬 .

**Comment by alexeybondarenko** [comment]
@oliviertassinari you mean about the meaningless diffs?  I would need to adjust a little bit the addon for storybook to avoid them. Or you are about something else?
