### ISSUE TITLE
show/hide screenshot is broken

### ISSUE THREAD

**Issue by nicgirault** [argos-ci/argos#348]
As a user, I can see my screenshots (Chrome 67)

### Detail

https://www.youtube.com/watch?v=QO-XZ23hRWc&feature=youtu.be

**Comment by oliviertassinari** [comment]
@nicgirault Hey something is off with the Collapse componnet.

**Comment by mbrookes** [comment]
Not sure why this was closed - it's been a problem since day 1, and still occurs:

![image](https://user-images.githubusercontent.com/357702/55554426-a6a1ed80-56da-11e9-9de4-395f0ae4bd62.png)

https://www.argos-ci.com/mui-org/material-ui/builds/45316

**Comment by gregberge** [comment]
Fixed
