### ISSUE TITLE
Missing reference screenshot

### ISSUE THREAD

**Issue by nicgirault** [argos-ci/argos#349]
As a user, I see a reference for each screenshot

![image](https://user-images.githubusercontent.com/551837/42173454-58e616be-7e1f-11e8-8a31-633e59d6377c.png)

@oliviertassinari I don't understand how to define the reference for each screenshot. I guess I didn't configure well my project. If you tell why I see only one screenshot on each line I would be glad to improve the documentation page with this information. Or is it really a bug? I would expect the reference screenshot to be the last screenshot on the target branch of the pull request.

**Comment by oliviertassinari** [comment]
@nicgirault We are using the default branch as reference. It's configured to be `master`. Are you running Argos-CI on your default branch?

**Comment by nicgirault** [comment]
On github my reference branch is `staging`. I didn't understand if it has to be master or if argos should use staging. Do we agree that it should use staging in my case? I run argos CI on staging but I did'nt merge yet on master

**Comment by oliviertassinari** [comment]
@nicgirault I have changed the baseline branch to staging. It should be good now.

**Comment by nicgirault** [comment]
@oliviertassinari thanks. I find argos CI super interesting. Would you like to work on a feature to allow changing the reference branch?

**Comment by oliviertassinari** [comment]
@nicgirault Yeah, we should be allowing people to change the default from the UI. Right now, it's simply a column in the database. I have been solving the problem with the support channel so far.

**Comment by nicgirault** [comment]
Sorry I missed so keys on my keyboard. I wanted to write "Would you like **me** to work on a feature to allow changing the reference branch?"

**Comment by oliviertassinari** [comment]
@nicgirault Oh yes, definitely! If you have some spare time, this would be awesome. There is some stuff in the stack I'm not proud of. At some point, I want to replace RxJs with react-apollo, the custom webpack config with Next.js. It's a move I have already done on another project 👌.

**Comment by oliviertassinari** [comment]
@neoziro If we push the paid private repository story forward, we would be able to paid for more workers on Heroku, providing faster builds to people. We have had around 500$ of expenses since the project started.

**Comment by neoziro** [comment]
@oliviertassinari I think the project is not ready for it, if we make user paid we have to create a real support and provide a consistent service. Let's talk about it soon.

**Comment by nicgirault** [comment]
@oliviertassinari could you also change the reference branch to staging on my new project `teach-app`? Sorry I didn't keep my commitment but I still keep in mind to work on a PR.

**Comment by oliviertassinari** [comment]
@nicgirault Done 👍.

**Comment by nicgirault** [comment]
@oliviertassinari we moved our reference branch back to master for `teach-app` and `student-app`. Could you change it again please 😬

![image](https://media.giphy.com/media/q0Fm9D20SCw5q/giphy.gif)

**Comment by oliviertassinari** [comment]
```sql
update repositories set "baselineBranch" = 'master' where name = 'student-app' or name = 'teach-app'
```

**Comment by ambreelmee** [comment]
Hello there! I'm also working with @nicgirault and it seems that we have the same issue for our project "landing". The reference branch should be "staging", would it be possible to change it for this project?
If it's something I can do by myself, please let me know how I should proceed :)
Thanks again for this project!
