### ISSUE TITLE
Credentials for the app `argos-dev`

### ISSUE THREAD

**Issue by rpellerin** [argos-ci/argos#350]
Hi,
The default credentials for the [argos-dev app](https://github.com/settings/connections/applications/c4636449f2df59e6010d) do not seem to be correct.
Namely, `c4636449f2df59e6010d` (client Id) and `1781c9a3e1d57fdcfdf9c29c02abf7d37e1c0427` (secret).
I get the following error:
![image](https://user-images.githubusercontent.com/5323445/48414604-841f3000-e74b-11e8-8746-b4404e881852.png)
Can you help please?
Thanks

**Comment by rpellerin** [comment]
nevermind, my `.env` was not up to date.

**Comment by oliviertassinari** [comment]
@rpellerin Should we update the values here?

**Comment by rpellerin** [comment]
No further action required, thanks! :)
