### ISSUE TITLE
As a user, I don't have unexpected diffs

### ISSUE THREAD

**Issue by fTrestour** [argos-ci/argos#353]
As a user, I don't have unexpected diffs:

### Motivation

Hi! As an Argos user I often have that kind of diffs:
![image](https://user-images.githubusercontent.com/14646596/50722954-5618f500-10d7-11e9-8e62-dc8c689c9c25.png)
They are not linked to what was developed between the before and after screenshots and I feel like these are false positives. Is there anything that can be done to avoid this?

I feel like something like [this](https://github.com/argos-ci/argos/issues/261) would allow me to avoid this.

**Comment by oliviertassinari** [comment]
@fTrestour Yes, we should move forward with #261. One possible alternative, for now, is to hide the background that causes the issue. I'm using the following CSS helper:
```css
.snapshot-background-none {
  background: none !important;
}
```
