### ISSUE TITLE
Test various mobile device and browser

### ISSUE THREAD

**Issue by tuan91** [argos-ci/argos#354]
Hi, is it possible to test various mobile devices and browser?
If so, how can I do that?
Thank you!

**Comment by tuan91** [comment]
Can I also test different browsers like firefox, chrome, safari?

**Comment by oliviertassinari** [comment]
@tuan91 We are only comparing screenshots.

**Comment by oliviertassinari** [comment]
As long as you push schreeshots with a different name for each browser, it will work as expected.
