### ISSUE TITLE
Screenshots are not displayed anymore

### ISSUE THREAD

**Issue by nicgirault** [argos-ci/argos#357]
As a user, I can see the screenshot images

Since Today I can't see anymore screenshots.

![image](https://user-images.githubusercontent.com/551837/53962483-796a1b80-40eb-11e9-988a-cb061f0363b2.png)

My png image does not seems corrupted. I can access them via circleci artifacts.

**Comment by oliviertassinari** [comment]
Same on Material-UI side: https://www.argos-ci.com/mui-org/material-ui/builds/43569.
@neoziro has removed some outdated data after integrating the changes Doctolib made to their internal fork. It's back online on Material-UI side, you should just need to rebuild the latest commit of your reference branch.

**Comment by neoziro** [comment]
Hello @nicgirault, as Olivier said, all screenshots have been removed. The project is free and AWS is expensive. Everything should work great for new builds! Sorry for the disagreement.
