### ISSUE TITLE
API: get buckets

### ISSUE THREAD

**Issue by neoziro** [argos-ci/argos#36]
### Motivation

Used internally by the CLI.

### Detail

- Method: GET
- Endpoint: /buckets?token&branch
- Response body:
```graphql
[
  {
    id
    name
    commit
    branch
    jobStatus
  }
]
```

**Comment by oliviertassinari** [comment]
On fait du graphQL ici ? Ça me semble un bon use case.

**Comment by neoziro** [comment]
@oliviertassinari I don't know if it's a good idea to mix GraphQL and REST API. And I think it's simpler for this use-case to use a simple REST API.
