### ISSUE TITLE
Incorrect diff when creating a PR to a different branch

### ISSUE THREAD

**Issue by mbrookes** [argos-ci/argos#364]
As a user, I want to create a PR that does not cause Argos to report a diff, when the PR is to a different branch

### Motivation

Better DX

### Detail

https://github.com/mui-org/material-ui/pull/15169

At the moment the default branch is `next`, this PR targets `master`. There should be no visual diff reported, but Argos is reporting differences between `master` and `next`: https://www.argos-ci.com/mui-org/material-ui/builds/45316

**Comment by neoziro** [comment]
Should be fixed by 4f111a3b288575651db74948476288ff2803b0d9
