### ISSUE TITLE
Link to build is broken on the list view

### ISSUE THREAD

**Issue by ThomasHarper** [argos-ci/argos#412]
As a user,

I'm trying to access a specific build through the list view.
If I click on the branch name on one of the build card, it takes to an unrelated build.
If I click on the build number (just right to the branch name), it takes me to the right build. However the build number displayed is incorrect (the link behind it is actually fine).

![1-3](https://user-images.githubusercontent.com/3199791/74169329-6e890680-4c2b-11ea-81d2-63d7b3f424c3.png)

**Comment by gregberge** [comment]
@ThomasHarper fix is ready to be deployed. Existing URL (in GitHub notifications) will be broken but new one should work fine. The number is now correct everywhere including in the URL.

**Comment by ThomasHarper** [comment]
@gregberge thank you for the fix :) Will inform the team about the previous links being broken.
