### ISSUE TITLE
How to enable github check?

### ISSUE THREAD

**Issue by shaodahong** [argos-ci/argos#423]
As a user,

### Motivation
In my see, argos support github app to intuitive view result, like

![image](https://user-images.githubusercontent.com/14831261/96951546-50480a00-151f-11eb-8099-b100585da5cc.png)

and authorized argos repository, relate pr https://github.com/ant-design/ant-design/pull/24475, but i can't find argos check

### Argos builds

https://www.argos-ci.com/ant-design/ant-design/builds

@gregberge thanks

**Comment by yoyo837** [comment]
Is the can be closed?

**Comment by shaodahong** [comment]
no, fork repository not effect

**Comment by shaodahong** [comment]
@gregberge Check status depend branch name or commit id or pull id?

**Comment by gregberge** [comment]
@shaodahong this is the commit, it should work out of the box if everything is correctly configured. What is exactly the problem?

**Comment by shaodahong** [comment]
https://github.com/ant-design/ant-design/pull/27394

Argos build
https://www.argos-ci.com/ant-design/ant-design/builds/57

in my see, it's upload correctly, but i can't find the check status

**Comment by shaodahong** [comment]
I use the azure pipeline, It only happens in the fork repository, maybe azure pipeline commit id is not correctly, but everything looks normal

![image](https://user-images.githubusercontent.com/14831261/97324032-5be35a00-18ac-11eb-87d0-b3a463e7c4eb.png)

**Comment by shaodahong** [comment]
Thanks for you reply, and it's resolved, reason is azure commit id it merge id, not commit id, i find a outside doc var `System.PullRequest.SourceCommitId`, it's good to me

**Comment by gregberge** [comment]
> Thanks for you reply, and it's resolved, reason is azure commit id it merge id, not commit id, i find a outside doc var `System.PullRequest.SourceCommitId`, it's good to me

Good!
