### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: Invalid user authorization

### ISSUE THREAD

**Issue by shaodahong** [argos-ci/argos#424]
As a user,

### Motivation
when click **mark as approved** console log js error `Uncaught (in promise) Error: GraphQL error: Invalid user authorization`

and I login in and has repository auth

### network

https://github.com/ant-design/ant-design/pull/27406#issuecomment-717209607

**Comment by gregberge** [comment]
@shaodahong I think there is a problem in the setup, will try to see what's going on

**Comment by gregberge** [comment]
@shaodahong only owner users have rights to approve it, I think you don't have authorization to do it because you are not part of the repository users. Are you admin or something like that on ant-design repository?

**Comment by shaodahong** [comment]
member of the ant-design repository, and if don't have authorization maybe we can hide approve button?

**Comment by gregberge** [comment]
> member of the ant-design repository, and if don't have authorization maybe we can hide approve button?

I just verified and you have right to click on it, yeah it should be hidden. We will fix it.

**Comment by shaodahong** [comment]
yep, i still has, another member of the team has a problem, he has the same identity as me @yoyo837, can help check he auth

**Comment by yoyo837** [comment]
So there are two problems here,
1. Two members of the same repo have different permissions in argos.
2. Buttons should be hidden or disabled without permission.
