### ISSUE TITLE
Diff with target branch

### ISSUE THREAD

**Issue by shaodahong** [argos-ci/argos#425]
As a user,

### Motivation
https://github.com/ant-design/ant-design has two base branch `master` and `feature`, and I see baselineBranch only one and default set the master, we can get target branch or use `argos-cli --targetBranch feature`

**Comment by shaodahong** [comment]
And fork this repo, and follow [Contributing](https://github.com/argos-ci/argos/blob/master/CONTRIBUTING.md) but local don't see any project if when i `yarn dev` and `yarn yarn procfile`

I registered OAuth app get client id and secret id, and set `.env` like this

![image](https://user-images.githubusercontent.com/14831261/97433886-29436b00-1959-11eb-83bf-04691674b429.png)

when click login and auth back to `localhost:4002`, still logout
![image](https://user-images.githubusercontent.com/14831261/97434119-83dcc700-1959-11eb-9711-2b5cce575110.png)

**Comment by gregberge** [comment]
It is possible to change it in the UI, not yet in a config or per upload.
