### ISSUE TITLE
More detailed documentation for Contributing

### ISSUE THREAD

**Issue by shaodahong** [argos-ci/argos#426]
And fork this repo, and follow [Contributing](https://github.com/argos-ci/argos/blob/master/CONTRIBUTING.md) but local don't see any project if when i `yarn dev` and `yarn yarn procfile`

I registered OAuth app get client id and secret id, and set `.env` like this

![image](https://user-images.githubusercontent.com/14831261/97433886-29436b00-1959-11eb-83bf-04691674b429.png)

when click login and auth back to `localhost:4002`, still logout
![image](https://user-images.githubusercontent.com/14831261/97434119-83dcc700-1959-11eb-9711-2b5cce575110.png)

_Originally posted by @shaodahong in https://github.com/argos-ci/argos/issues/425#issuecomment-717891923_

**Comment by gregberge** [comment]
Should be OK, it is updated.
