### ISSUE TITLE
socket hang up when upload

### ISSUE THREAD

**Issue by shaodahong** [argos-ci/argos#429]
As a user,

### Motivation

appeared twice, I tried for a week, when i use `argos-ci upload dir`

```bash
✘  Sorry an error happened:
request to https://api.argos-ci.com/builds failed, reason: socket hang up
FetchError: request to https://api.argos-ci.com/builds failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/vsts/work/1/s/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at TLSSocket.socketOnEnd (_http_client.js:493:9)
    at TLSSocket.emit (events.js:326:22)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by gregberge** [comment]
Hmm weird, maybe you have too many screenshots to be uploaded in one time, try to use the batch mode.

**Comment by shaodahong** [comment]
> Hmm weird, maybe you have too many screenshots to be uploaded in one time, try to use the batch mode.

About 500 screenshots

**Comment by shaodahong** [comment]
new Error https://github.com/ant-design/ant-design/pull/27546/checks?check_run_id=1351958056

```bash
=== argos-cli: uploading 'imageSnapshots' directory...

i  using `pull/27546/merge` as branch
i  using `590a5e764c61cbd61f2ad7e7de1f37a11af3fdd0` as commit
i  found 484 screenshots to upload

✘  Sorry an error happened:
invalid json response body at https://api.argos-ci.com/builds reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at https://api.argos-ci.com/builds reason: Unexpected token < in JSON at position 0
    at /home/runner/work/ant-design/ant-design/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.<anonymous> (/home/runner/work/ant-design/ant-design/node_modules/argos-cli/lib/index.js:54:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! antd@4.8.0 argos: `argos upload imageSnapshots "--token" "***" "--branch" "pull/27546/merge" "--commit" "590a5e764c61cbd61f2ad7e7de1f37a11af3fdd0"`
npm ERR! Exit status 1

```

**Comment by shaodahong** [comment]
Maybe we can retry three times to avoid unstable uploads？

**Comment by gregberge** [comment]
I think you should use the batch mode and upload them in several times. Anyway the upload code is not nice, it should handle it and it should not call our server but upload them to S3 directly.

**Comment by shaodahong** [comment]
thanks and I try batch mode

**Comment by shaodahong** [comment]
I use `--batchCount 3` but after **Upload complete!** not find screenshot, what should I do？

**Comment by gregberge** [comment]
--external-build-id is the key that links your batch. So you have to do three times:

```js
argos upload snap --token ** --batchCount 3 --external-build-id 123
```

**Comment by shaodahong** [comment]
@oliviertassinari Mui also has

https://app.circleci.com/pipelines/github/mui-org/material-ui/26698/workflows/5614be70-56f1-42f4-8bbd-328fc7b42acd/jobs/195419

**Comment by oliviertassinari** [comment]
@shaodahong Thanks for the ping. Yeah, this sounds like a good idea. We start to have enough screenshot to justify spending time on this.

**Comment by oliviertassinari** [comment]
I have tried to make it work in https://github.com/mui-org/material-ui/pull/23518 but I get the same error as @shaodahong 

> argos upload test/regressions/screenshots/chrome/0 --token ******************************** --batchCount 3 --external-build-id dfda12ad7cd840730ac8b0f2c26cfb3761a56de5

> found 125 screenshots to upload

> ❌ insert into "build_notifications" ("buildId", "createdAt", "jobStatus", "type", "updatedAt") values ($1, $2, $3, $4, $5) returning "id" - insert or update on table "build_notifications" violates foreign key constraint "build_notifications_buildid_foreign"

**Comment by gregberge** [comment]
@oliviertassinari it is weird, it is used every day by Doctolib and it works. I will have to investigate it further. Ping @jsfez

**Comment by oliviertassinari** [comment]
I don't understand the SQL error. I think that I will wait for the timeout to happen more frequently before looking into what is wrong in more detail, for now, it happened once.

**Comment by shaodahong** [comment]
yep, it's too weird, like missing some param

**Comment by gregberge** [comment]
@bpaquet from Doctolib has fixed the bug, @oliviertassinari @shaodahong could you try again?

**Comment by bpaquet** [comment]
The insert build_notification was not included in the transaction so the foreign key was failing.

**Comment by shaodahong** [comment]
In my local, still has, i need update some deps?

**Comment by shaodahong** [comment]
@bpaquet thanks, now resolved

@gregberge and snap dir hava a image, but  I run `yarn argos upload snap --token *** --batchCount 2 --branch test --commit 811102b105fa2b5fbb5222d50d5521bc909f7790 --external-build-id 'v1.1.2'` twice, get two identical pictures

https://www.argos-ci.com/shaodahong/jd-happy/builds/10

Is this right?

**Comment by gregberge** [comment]
@shaodahong yeah it is right, we do not deduplicate images between batches for now. Maybe you could add a command to split screenshots into several directories.

Anyway the batch mode will not be required in future for a large number of screenshots, but as of today it is the only solution I have for you!

**Comment by shaodahong** [comment]
thanks for your help

**Comment by shaodahong** [comment]
and I find use batch mode can't generate diff img

https://www.argos-ci.com/shaodahong/jd-happy/builds/15
