### ISSUE TITLE
Lost github check state

### ISSUE THREAD

**Issue by shaodahong** [argos-ci/argos#434]
As a user,

### Motivation
Commit https://github.com/ant-design/ant-design/commit/d9cc4c2af9b088621e9297cbac3c83d400016d3c
Argos build https://www.argos-ci.com/ant-design/ant-design/builds/175

Argos github check state depend commit id, and I saw upload success but can't find argos-ci github app check state

![image](https://user-images.githubusercontent.com/14831261/108648771-05eb8f80-74f7-11eb-96e9-77be928ca6a2.png)
![image](https://user-images.githubusercontent.com/14831261/108648815-113ebb00-74f7-11eb-93f0-f5360ebab345.png)

**Comment by shaodahong** [comment]
And I found app broken happen when newly installed Argos

**Comment by afc163** [comment]
Any response?

**Comment by gregberge** [comment]
I fixed transactions, it should be the source of the problem.

**Comment by shaodahong** [comment]
Thanks, and reinstall or other method?

**Comment by gregberge** [comment]
@shaodahong if it is not fixed, then reinstall is probably a good move.
