### ISSUE TITLE
PDF screenshots

### ISSUE THREAD

**Issue by ThHareau** [argos-ci/argos#442]
As a user, I would like to be able to take screenshots of PDF documents. 

### Motivation

We are generating PDF in our application, and we would like to take screenshots from them. 

### Detail

This is not possible with argos, so we are displaying the PDF in the application and taking a screenshot of each page. This is quite slow, tends to be flaky on mutli-page documents and quite ugly in the code. 

Ideally this could be handled by argos directly: when receiving a PDF, it could be converted to an image thanks to image magick, and the actual screenshot management could be launched against it. 

Note that we could do this in our codebase, however I find it a bit of sorrow considering that argos is specialized in image manipulation whereas we are not.

**Comment by gregberge** [comment]
Argos does not take screenshots, it only compares them.
