### ISSUE TITLE
Uploading screenshots fail

### ISSUE THREAD

**Issue by michaldudak** [argos-ci/argos#483]
For the last 2 days, we're having problems with uploading screenshots to Argos from our CI. 
The task usually (not always, though - some times it succeeds) fails with the following error:

```
✘  Sorry an error happened:
503: Failed to parse response body as JSON:

<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>
```

See https://app.circleci.com/pipelines/github/mui/material-ui/80166/workflows/e3ffed6b-1b23-413d-9be2-cdcee2dab8c5/jobs/423454 for the logs on our side.

**Comment by gregberge** [comment]
Hello @michaldudak, please migrate to the new CLI, the legacy one (argos-cli) will stop to work soon.

https://docs.argos-ci.com/argos-cli

If you experience that after migrating, please open a new issue.

**Comment by michaldudak** [comment]
The new CLI requires Node 16. Is this a hard dependency or could you consider allowing v14?

**Comment by gregberge** [comment]
@michaldudak still needed?

**Comment by Crash--** [comment]
@gregberge At [cozy](https://app.argos-ci.com/cozy/cozy-ui/builds) we rely a lot on argos for our components librairie based on mui. Thanks for the hard work! 

I understand that you have issue with the server and you're currently working to fix the issue (https://github.com/argos-ci/argos/issues/490)

I want to talk about `argos-cli`. You say that `it's legacy and will stop to work soon`. When you say soon, do you have a date in mind? We'll migrate to the new cli, but I didn't see any depreciation message when reaching argos API or else to say that we need to migrate. Maybe it's just me and I don't look at the right place. 

Is there a way to be aware of the changes to be made in order to be able to still use the service? (and before having an error from your API saying that we use an outdated cli?)

Thanks

**Comment by gregberge** [comment]
@Crash-- since Argos is early and totally free we took the decision to suspend the previous CLI. The new one optimizes cost, so it is important for us.

To continue using Argos, you have to migrate to the new CLI, the migration should be easy!

**Comment by Crash--** [comment]
> @Crash-- since Argos is early and totally free we took the decision to suspend the previous CLI. The new one optimizes cost, so it is important for us.

Give me a way to contact you (discord link is broken, twitter is suspended and there is no other way on your website) to talk about that specific point ;). 

> To continue using Argos, you have to migrate to the new CLI, the migration should be easy!

OK, we'll try to upgrade today. Thanks. 

But still, having a message somewhere saying that we have to upgrade is missing in my opinion.

**Comment by gregberge** [comment]
@Crash-- please join our Discord https://discord.gg/vMyXWVA8

**Comment by gregberge** [comment]
> But still, having a message somewhere saying that we have to upgrade is missing in my opinion.

The message should appear in the result of `argos upload` on your CI.

**Comment by Crash--** [comment]
We currently only have heroku error: 

```
=== argos-cli: uploading 'screenshots/reactDesktop/' directory...

i  identified `travis` environment

i  using `feat/Display-more-qualification-attributes-in-the-viewer` as branch

i  using `325015b1fcdfb3e260b45cbfc914a6232cf8c2aa` as commit

i  found 428 screenshots to upload

✘  Sorry an error happened:

503: Failed to parse response body as JSON:

<!DOCTYPE html>

	<html>

	  <head>

		<meta name="viewport" content="width=device-width, initial-scale=1">

		<meta charset="utf-8">

		<title>Application Error</title>

		<style media="screen">

		  html,body,iframe {

			margin: 0;

			padding: 0;

		  }

		  html,body {

			height: 100%;

			overflow: hidden;

		  }

		  iframe {

			width: 100%;

			height: 100%;

			border: 0;

		  }

		</style>

	  </head>

	  <body>

		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>

	  </body>

	</html>

Error: 503: Failed to parse response body as JSON:

<!DOCTYPE html>

	<html>

	  <head>

		<meta name="viewport" content="width=device-width, initial-scale=1">

		<meta charset="utf-8">

		<title>Application Error</title>

		<style media="screen">

		  html,body,iframe {

			margin: 0;

			padding: 0;

		  }

		  html,body {

			height: 100%;

			overflow: hidden;

		  }

		  iframe {

			width: 100%;

			height: 100%;

			border: 0;

		  }

		</style>

	  </head>

	  <body>

		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>

	  </body>

	</html>

    at Command.<anonymous> (/home/travis/build/cozy/cozy-ui/node_modules/argos-cli/lib/index.js:59:13)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gregberge** [comment]
@Crash-- I am on it, I don't really understand why it is going on but I will find it.

**Comment by Crash--** [comment]
For others people that need to upgrade to `@argos-ci/cli` 

`--branch` & `--commit` are not supported anymore. But if you use travis (I don't know for others CI), detection is done automatically. So you can remove them.

`--batchCount`  can be replaced by `--parallel-total`
`-external-build-id` can be replaced by `--parallel-nonce`
