### ISSUE TITLE
Flag screenshot as "Flaky"

### ISSUE THREAD

**Issue by jsfez** [argos-ci/argos#731]
Nothing

**Comment by jsfez** [comment]
It's not client's request. He will think about it if it become a priority.

**Comment by gregberge** [comment]
Actually it is and flaky score is not.

**Comment by jsfez** [comment]
![Image](https://user-images.githubusercontent.com/15954562/219884680-d458dd93-bd41-413e-a09a-0ca2129f9eb6.png)
