### ISSUE TITLE
Compare UI against the designs in Figma, Invision or Sketch.

### ISSUE THREAD

**Issue by chitralverma** [argos-ci/argos#751]
As a user, I would like to compare my developed UI against the designed mock-up screens.

Usually, the designs for such mock-ups are present in a design tool like Sketch, Figma or Invision.

### Motivation
In the case of professional UI development, the developed UI doesn't always resemble the designs done by the design team in tools like Figma, Invision etc. The idea is based on image comparison just like it is right now in Argos where the CI takes screenshots and compares them with designs in the design tools.

**Comment by jsfez** [comment]
Hi Chitral,

Thank you for your suggestion. I agree that this feature would be useful for our users. I'd like to discuss this idea further and explore how we can address this need in Argos.

We should continue the conversation on [Argos' Discord server](https://discord.gg/WjzGrQGS4A). If you're not a Discord user, feel free to schedule a call with me through [my Calendly](https://calendly.com/jeremy-186/argos)

Looking forward to discussing this further with you.

**Comment by gregberge** [comment]
We will not do it, it's not the focus of Argos.
