### ISSUE TITLE
Replace Jest by mocha / chai / sinon / proxyquire

### ISSUE THREAD

**Issue by neoziro** [argos-ci/argos#98]
Jest is :

- slow
- not good for displaying errors
- hasn't a good assertion system
- hasn't a good mocking system

**Comment by oliviertassinari** [comment]
🚨 the latest version of jest introduce an important memory leak. Don't try do upgrade it.

**Comment by neoziro** [comment]
Not sure it's a good choice for now.

**Comment by oliviertassinari** [comment]
We will see later 👍
